/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/checkout_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a checkout session
         * @description Initializes a new checkout session from items and (optionally) buyer and fulfillment info.
         *     MUST return 201 with a rich, authoritative cart state.
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout_sessions/{checkout_session_id}": {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        /**
         * Retrieve a checkout session
         * @description Returns the latest authoritative state for the checkout session.
         */
        get: operations["getCheckoutSession"];
        put?: never;
        /**
         * Update a checkout session
         * @description Applies changes (items, fulfillment address, fulfillment option) and returns an updated authoritative cart state.
         */
        post: operations["updateCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout_sessions/{checkout_session_id}/complete": {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Content-Type": components["parameters"]["ContentType"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a checkout session
         * @description Finalizes the checkout by applying a payment method. MUST create an order and return completed state on success.
         */
        post: operations["completeCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout_sessions/{checkout_session_id}/cancel": {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a checkout session
         * @description Cancels a session if not already completed or canceled.
         */
        post: operations["cancelCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            name: string;
            line_one: string;
            line_two?: string;
            city: string;
            state: string;
            country: string;
            postal_code: string;
        };
        Buyer: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            phone_number?: string;
        };
        Item: {
            id: string;
            quantity: number;
        };
        PaymentProvider: {
            /** @enum {string} */
            provider: "stripe";
            supported_payment_methods: "card"[];
        };
        LineItem: {
            id: string;
            item: components["schemas"]["Item"];
            base_amount: number;
            discount: number;
            subtotal: number;
            tax: number;
            total: number;
        };
        Total: {
            /** @enum {string} */
            type: "items_base_amount" | "items_discount" | "subtotal" | "discount" | "fulfillment" | "tax" | "fee" | "total";
            display_text: string;
            amount: number;
        };
        FulfillmentOptionShipping: {
            /** @constant */
            type: "shipping";
            id: string;
            title: string;
            subtitle?: string;
            carrier?: string;
            /** Format: date-time */
            earliest_delivery_time?: string;
            /** Format: date-time */
            latest_delivery_time?: string;
            subtotal: string;
            tax: string;
            total: string;
        };
        FulfillmentOptionDigital: {
            /** @constant */
            type: "digital";
            id: string;
            title: string;
            subtitle?: string;
            subtotal: string;
            tax: string;
            total: string;
        };
        MessageInfo: {
            /** @constant */
            type: "info";
            /** @description RFC 9535 JSONPath */
            param?: string;
            /** @enum {string} */
            content_type: "plain" | "markdown";
            content: string;
        };
        MessageError: {
            /** @constant */
            type: "error";
            /** @enum {string} */
            code: "missing" | "invalid" | "out_of_stock" | "payment_declined" | "requires_sign_in" | "requires_3ds";
            /** @description RFC 9535 JSONPath */
            param?: string | null;
            /** @enum {string} */
            content_type: "plain" | "markdown";
            content: string;
        };
        Link: {
            /** @enum {string} */
            type: "terms_of_use" | "privacy_policy" | "seller_shop_policies";
            /** Format: uri */
            url: string;
        };
        PaymentData: {
            token: string;
            /** @enum {string} */
            provider: "stripe";
            billing_address?: components["schemas"]["Address"];
        };
        Order: {
            id: string;
            checkout_session_id: string;
            /** Format: uri */
            permalink_url: string;
        };
        CheckoutSessionBase: {
            id: string;
            buyer?: components["schemas"]["Buyer"];
            payment_provider?: components["schemas"]["PaymentProvider"];
            /** @enum {string} */
            status: "not_ready_for_payment" | "ready_for_payment" | "completed" | "canceled" | "in_progress";
            currency: string;
            line_items: components["schemas"]["LineItem"][];
            fulfillment_address?: components["schemas"]["Address"];
            fulfillment_options: (components["schemas"]["FulfillmentOptionShipping"] | components["schemas"]["FulfillmentOptionDigital"])[];
            fulfillment_option_id?: string;
            totals: components["schemas"]["Total"][];
            messages: (components["schemas"]["MessageInfo"] | components["schemas"]["MessageError"])[];
            links: components["schemas"]["Link"][];
        };
        CheckoutSession: components["schemas"]["CheckoutSessionBase"];
        CheckoutSessionWithOrder: components["schemas"]["CheckoutSessionBase"] & {
            order: components["schemas"]["Order"];
        };
        CheckoutSessionCreateRequest: {
            buyer?: components["schemas"]["Buyer"];
            items: components["schemas"]["Item"][];
            fulfillment_address?: components["schemas"]["Address"];
        };
        CheckoutSessionUpdateRequest: {
            buyer?: components["schemas"]["Buyer"];
            items?: components["schemas"]["Item"][];
            fulfillment_address?: components["schemas"]["Address"];
            fulfillment_option_id?: string;
        };
        CheckoutSessionCompleteRequest: {
            buyer?: components["schemas"]["Buyer"];
            payment_data: components["schemas"]["PaymentData"];
        };
        Error: {
            /** @enum {string} */
            type: "invalid_request" | "request_not_idempotent" | "processing_error" | "service_unavailable";
            /** @description Implementation-defined error code */
            code: string;
            message: string;
            /** @description RFC 9535 JSONPath (optional) */
            param?: string;
        };
    };
    responses: never;
    parameters: {
        Authorization: string;
        ContentType: string;
        AcceptLanguage: string;
        UserAgent: string;
        IdempotencyKey: string;
        RequestId: string;
        Signature: string;
        Timestamp: string;
        APIVersion: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Content-Type": components["parameters"]["ContentType"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Echo of the request idempotency key */
                    "Idempotency-Key"?: string;
                    /** @description Echo of the request correlation id */
                    "Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Content-Type": components["parameters"]["ContentType"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionCompleteRequest"];
            };
        };
        responses: {
            /** @description Completed session with order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionWithOrder"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                Authorization: components["parameters"]["Authorization"];
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                "User-Agent"?: components["parameters"]["UserAgent"];
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "Request-Id"?: components["parameters"]["RequestId"];
                Signature?: components["parameters"]["Signature"];
                Timestamp?: components["parameters"]["Timestamp"];
                "API-Version": components["parameters"]["APIVersion"];
            };
            path: {
                checkout_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canceled session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Not cancelable (already completed/canceled) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
